language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
deploy:
  provider: heroku
  api_key:
    secure: d7Ki9vXXBJo84BuHgYZbn5Ax85/X0C4fDfdGxL5PXrXMehzKqiqE+qcJ/xbq1f9WQlsRSaEZuRYFmqXLEGFaJFU9Sb4XIavDooH/jiLicOR30C0haVewJ++VkxxY7FERU+NjlML8srvcRfddEyrbRmrfSZ4y0d3eiTWML41NMro=
  app: daon-voice-app
  skip_cleanup: true